---

- name: Make sure Liferay system group exists
  sudo: yes
  group: name={{ liferay_os_group }} state=present

- name: Make sure Liferay system user exists
  sudo: yes
  user: name={{ liferay_os_user }} group={{ liferay_os_group }}

- name: Get the tomcat folder 
  action: 
     shell ls {{ liferay_home }} | grep tomcat | head -1
  register: get_liferay_tomcat

- file:
    path: "{{ liferay_home }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: "{{ liferay_os_user }}"
    group: "{{ liferay_os_group }}"

- set_fact:
    liferay_tomcat_folder: "{{ get_liferay_tomcat.stdout }}"
  
- name: Add liferay service
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  template: src=liferay.service dest=/usr/lib/systemd/system/liferay.service mode=0660
  
- service:
    name: liferay
    enabled: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    state: started
